import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReportService } from '../../services/report.service';

@Component({
  selector: 'app-report',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="reports-page">
      <div class="page-header">
        <div class="header-left">
          <h1>📊 Medical Reports</h1>
          <p>Download AI-generated health reports in PDF or DOCX format</p>
        </div>
        <button class="refresh-btn" (click)="loadReports()">🔄 Refresh</button>
      </div>

      <!-- Reports Empty State -->
      <div class="empty-state" *ngIf="reports.length === 0 && !loading">
        <div class="empty-icon">📋</div>
        <h2>No Reports Yet</h2>
        <p>Upload and analyze a medical document first, then generate reports from the Documents page.</p>
        <a href="/documents" class="goto-docs-btn">📄 Go to Documents</a>
      </div>

      <div class="loading-state" *ngIf="loading">
        <div class="loader">Loading your reports...</div>
      </div>

      <!-- Reports Grid -->
      <div class="reports-grid" *ngIf="reports.length > 0">
        <div class="report-card" *ngFor="let report of reports">
          <div class="report-header">
            <div class="report-icon">📊</div>
            <div class="report-meta">
              <div class="report-title">{{ report.reportTitle }}</div>
              <div class="report-date">{{ report.generatedAt | date:'MMM dd, yyyy HH:mm' }}</div>
            </div>
            <div class="report-badge">{{ report.reportType?.replace('_', ' ') }}</div>
          </div>

          <div class="report-summary" *ngIf="report.summary">
            <div class="summary-label">Summary</div>
            <div class="summary-text">{{ report.summary | slice:0:300 }}{{ report.summary?.length > 300 ? '...' : '' }}</div>
          </div>

          <div class="report-actions">
            <button class="download-btn pdf-btn" (click)="downloadPDF(report.id)" [disabled]="downloading[report.id]">
              <span *ngIf="!downloading[report.id + '_pdf']">📥 Download PDF</span>
              <span *ngIf="downloading[report.id + '_pdf']">⟳ Downloading...</span>
            </button>
            <button class="download-btn docx-btn" (click)="downloadDOCX(report.id)" [disabled]="downloading[report.id]">
              <span *ngIf="!downloading[report.id + '_docx']">📥 Download DOCX</span>
              <span *ngIf="downloading[report.id + '_docx']">⟳ Downloading...</span>
            </button>
          </div>

          <div class="alert success" *ngIf="successMsg[report.id]">✅ {{ successMsg[report.id] }}</div>
          <div class="alert error" *ngIf="errorMsg[report.id]">❌ {{ errorMsg[report.id] }}</div>
        </div>
      </div>

      <!-- Info Box -->
      <div class="info-box" *ngIf="reports.length > 0">
        <div class="info-icon">ℹ️</div>
        <div class="info-text">
          <strong>AI-Generated Reports</strong> — These reports are generated by HealthAI's multi-agent system
          using Gemini 2.5 Flash Lite, RAG retrieval, and specialized medical analysis agents.
          Reports include detailed analysis and personalized health suggestions.
          <br><br>
          <em>⚠️ Disclaimer: AI reports are for informational purposes only. Always consult a qualified
          healthcare professional for medical decisions.</em>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .reports-page { padding: 32px; max-width: 1200px; margin: 0 auto; color: #e0e6f0; }
    .page-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; }
    .header-left h1 { font-size: 26px; font-weight: 700; color: #fff; margin: 0 0 8px; }
    .header-left p { color: rgba(255,255,255,0.4); font-size: 15px; margin: 0; }
    .refresh-btn {
      padding: 8px 16px;
      background: rgba(255,255,255,0.04);
      border: 1px solid rgba(255,255,255,0.1);
      border-radius: 8px;
      color: rgba(255,255,255,0.6);
      font-size: 13px;
      cursor: pointer;
      transition: all 0.2s;
    }
    .refresh-btn:hover { background: rgba(255,255,255,0.08); }

    .empty-state {
      text-align: center;
      padding: 80px 20px;
    }
    .empty-icon { font-size: 64px; margin-bottom: 24px; }
    .empty-state h2 { font-size: 24px; color: #fff; margin: 0 0 12px; }
    .empty-state p { color: rgba(255,255,255,0.4); font-size: 15px; margin-bottom: 28px; }
    .goto-docs-btn {
      padding: 12px 28px;
      background: linear-gradient(135deg, #00c8ff, #0070ff);
      color: white;
      text-decoration: none;
      border-radius: 10px;
      font-size: 15px;
      font-weight: 600;
      transition: all 0.2s;
      display: inline-block;
    }
    .goto-docs-btn:hover { transform: translateY(-2px); opacity: 0.9; }

    .loading-state { text-align: center; padding: 64px; color: rgba(255,255,255,0.4); font-size: 16px; }

    .reports-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(400px, 1fr)); gap: 20px; margin-bottom: 32px; }

    .report-card {
      background: rgba(255,255,255,0.03);
      border: 1px solid rgba(255,255,255,0.07);
      border-radius: 16px;
      padding: 24px;
      transition: border-color 0.2s;
    }
    .report-card:hover { border-color: rgba(255,255,255,0.15); }

    .report-header { display: flex; align-items: flex-start; gap: 14px; margin-bottom: 16px; }
    .report-icon { font-size: 32px; flex-shrink: 0; }
    .report-meta { flex: 1; min-width: 0; }
    .report-title { font-size: 15px; color: #fff; font-weight: 600; margin-bottom: 6px; line-height: 1.3; }
    .report-date { font-size: 12px; color: rgba(255,255,255,0.3); }
    .report-badge {
      padding: 4px 10px;
      background: rgba(0,200,255,0.08);
      border: 1px solid rgba(0,200,255,0.2);
      border-radius: 12px;
      font-size: 11px;
      color: #00c8ff;
      white-space: nowrap;
      font-weight: 600;
      flex-shrink: 0;
    }

    .report-summary {
      background: rgba(0,0,0,0.2);
      border-radius: 10px;
      padding: 14px;
      margin-bottom: 18px;
    }
    .summary-label { font-size: 11px; color: rgba(255,255,255,0.3); text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px; }
    .summary-text { font-size: 13px; color: rgba(255,255,255,0.55); line-height: 1.6; }

    .report-actions { display: flex; gap: 10px; flex-wrap: wrap; margin-bottom: 12px; }
    .download-btn {
      display: flex;
      align-items: center;
      gap: 6px;
      padding: 10px 20px;
      border-radius: 8px;
      font-size: 13px;
      font-weight: 600;
      cursor: pointer;
      border: 1px solid;
      transition: all 0.2s;
    }
    .download-btn:disabled { opacity: 0.5; cursor: not-allowed; }
    .pdf-btn {
      background: rgba(255,80,80,0.08);
      border-color: rgba(255,80,80,0.25);
      color: #ff8080;
    }
    .pdf-btn:hover:not(:disabled) { background: rgba(255,80,80,0.15); }
    .docx-btn {
      background: rgba(0,100,255,0.08);
      border-color: rgba(0,100,255,0.25);
      color: #4488ff;
    }
    .docx-btn:hover:not(:disabled) { background: rgba(0,100,255,0.15); }

    .alert {
      padding: 10px 14px;
      border-radius: 8px;
      font-size: 13px;
      margin-top: 8px;
    }
    .alert.success { background: rgba(0,200,100,0.08); border: 1px solid rgba(0,200,100,0.2); color: #00cc88; }
    .alert.error { background: rgba(255,60,60,0.08); border: 1px solid rgba(255,60,60,0.2); color: #ff6060; }

    .info-box {
      display: flex;
      gap: 16px;
      padding: 20px;
      background: rgba(0,200,255,0.04);
      border: 1px solid rgba(0,200,255,0.1);
      border-radius: 12px;
    }
    .info-icon { font-size: 24px; flex-shrink: 0; }
    .info-text { font-size: 13px; color: rgba(255,255,255,0.45); line-height: 1.7; }
    .info-text strong { color: rgba(255,255,255,0.7); }
    .info-text em { color: rgba(255,200,0,0.6); }
  `]
})
export class ReportComponent implements OnInit {
  reports: any[] = [];
  loading = false;
  downloading: { [key: string]: boolean } = {};
  successMsg: { [key: number]: string } = {};
  errorMsg: { [key: number]: string } = {};

  constructor(private reportService: ReportService) {}

  ngOnInit() { this.loadReports(); }

  loadReports() {
    this.loading = true;
    this.reportService.getReports().subscribe({
      next: (reports) => { this.reports = reports; this.loading = false; },
      error: () => { this.loading = false; }
    });
  }

  downloadPDF(reportId: number) {
    const key = reportId + '_pdf';
    this.downloading[key] = true;
    this.successMsg[reportId] = '';
    this.errorMsg[reportId] = '';

    this.reportService.downloadPDF(reportId).subscribe({
      next: (blob) => {
        this.triggerDownload(blob, `HealthReport_${reportId}.pdf`);
        this.successMsg[reportId] = 'PDF downloaded successfully!';
        this.downloading[key] = false;
        setTimeout(() => { this.successMsg[reportId] = ''; }, 4000);
      },
      error: () => {
        this.errorMsg[reportId] = 'PDF download failed. Please try again.';
        this.downloading[key] = false;
        setTimeout(() => { this.errorMsg[reportId] = ''; }, 4000);
      }
    });
  }

  downloadDOCX(reportId: number) {
    const key = reportId + '_docx';
    this.downloading[key] = true;
    this.successMsg[reportId] = '';
    this.errorMsg[reportId] = '';

    this.reportService.downloadDOCX(reportId).subscribe({
      next: (blob) => {
        this.triggerDownload(blob, `HealthReport_${reportId}.docx`);
        this.successMsg[reportId] = 'DOCX downloaded successfully!';
        this.downloading[key] = false;
        setTimeout(() => { this.successMsg[reportId] = ''; }, 4000);
      },
      error: () => {
        this.errorMsg[reportId] = 'DOCX download failed. Please try again.';
        this.downloading[key] = false;
        setTimeout(() => { this.errorMsg[reportId] = ''; }, 4000);
      }
    });
  }

  private triggerDownload(blob: Blob, filename: string) {
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  }
}
